import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {sqlite} from './database';
export const settingKeys=['AI_PROVIDER','AI_MODEL','OPENAI_API_KEY','OPENROUTER_API_KEY','CHEAPERINFERENCE_API_KEY','SMTP_HOST','SMTP_PORT','SMTP_USER','SMTP_PASSWORD','SMTP_FROM','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','PAYPAL_CLIENT_ID','PAYPAL_CLIENT_SECRET','PAYPAL_WEBHOOK_ID','PAYPAL_MODE','RAZORPAY_KEY_ID','RAZORPAY_KEY_SECRET','RAZORPAY_WEBHOOK_SECRET','INPUT_COST_PER_MILLION','OUTPUT_COST_PER_MILLION','MONTHLY_FIXED_COST_USD','PAYMENT_FEE_PERCENT','USD_INR_RATE'] as const;
export type SettingKey=typeof settingKeys[number];
export const secretKeys=new Set<string>(['OPENAI_API_KEY','OPENROUTER_API_KEY','CHEAPERINFERENCE_API_KEY','SMTP_PASSWORD','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','PAYPAL_CLIENT_SECRET','RAZORPAY_KEY_SECRET','RAZORPAY_WEBHOOK_SECRET']);
function encryptionKey(){const v=process.env.SETTINGS_ENCRYPTION_KEY;if(!v||!/^([a-f0-9]{64})$/i.test(v))throw new Error('SETTINGS_ENCRYPTION_KEY must be 32 random bytes in hexadecimal.');return Buffer.from(v,'hex')}
export function seal(value:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',encryptionKey(),iv);return Buffer.concat([iv,c.update(value,'utf8'),c.final(),c.getAuthTag()]).toString('base64')}
export function unseal(value:string){const b=Buffer.from(value,'base64');if(b.length<28)throw new Error('Invalid encrypted setting');const d=createDecipheriv('aes-256-gcm',encryptionKey(),b.subarray(0,12),{authTagLength:16});d.setAuthTag(b.subarray(-16));return Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString('utf8')}
export function setting(key:string,fallback=''){const row=sqlite().prepare('SELECT value FROM settings WHERE key=?').get(key);return row?unseal(String(row.value)):process.env[key]||fallback}
export function settingsConfig(){const rows=sqlite().prepare('SELECT key,value FROM settings').all();const values=Object.fromEntries(rows.map(row=>[String(row.key),unseal(String(row.value))]));return Object.fromEntries(settingKeys.map(k=>[k,values[k]??process.env[k]??'']))}
export function publicSettings(){return Object.fromEntries(settingKeys.map(k=>[k,secretKeys.has(k)?{configured:!!setting(k)}:setting(k)]))}
export function saveSettings(values:Record<string,string>){const d=sqlite();d.exec('BEGIN IMMEDIATE');try{for(const [key,value] of Object.entries(values)){if(!settingKeys.includes(key as SettingKey))throw new Error('Unknown setting');if(secretKeys.has(key)&&value==='')continue;d.prepare('INSERT INTO settings VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').run(key,seal(value),new Date().toISOString())}d.exec('COMMIT')}catch(e){d.exec('ROLLBACK');throw e}}
