import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto';
import {sqlite} from './database';
export const settingKeys=['AI_PROVIDER','AI_MODEL','OPENAI_API_KEY','OPENROUTER_API_KEY','CHEAPERINFERENCE_API_KEY','ANTHROPIC_API_KEY','REPLICATE_API_TOKEN','SMTP_HOST','SMTP_PORT','SMTP_USER','SMTP_PASSWORD','SMTP_FROM','GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','PAYPAL_CLIENT_ID','PAYPAL_CLIENT_SECRET','PAYPAL_WEBHOOK_ID','PAYPAL_MODE','RAZORPAY_KEY_ID','RAZORPAY_KEY_SECRET','RAZORPAY_WEBHOOK_SECRET','INPUT_COST_PER_MILLION','OUTPUT_COST_PER_MILLION','MONTHLY_FIXED_COST_USD','PAYMENT_FEE_PERCENT','USD_INR_RATE'] as const;
export type SettingKey=typeof settingKeys[number];
export const secretKeys=new Set<string>(['OPENAI_API_KEY','OPENROUTER_API_KEY','CHEAPERINFERENCE_API_KEY','ANTHROPIC_API_KEY','REPLICATE_API_TOKEN','SMTP_PASSWORD','GOOGLE_CLIENT_SECRET','STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','PAYPAL_CLIENT_SECRET','RAZORPAY_KEY_SECRET','RAZORPAY_WEBHOOK_SECRET']);
function encryptionKey(){const v=process.env.SETTINGS_ENCRYPTION_KEY||process.env.AUTH_SECRET||'quickietimeappqtaiclick';if(/^([a-f0-9]{64})$/i.test(v))return Buffer.from(v,'hex');return createHash('sha256').update(v).digest()}
export function seal(value:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',encryptionKey(),iv);return Buffer.concat([iv,c.update(value,'utf8'),c.final(),c.getAuthTag()]).toString('base64')}
export function unseal(value:string){const b=Buffer.from(value,'base64');if(b.length<28)throw new Error('Invalid encrypted setting');const d=createDecipheriv('aes-256-gcm',encryptionKey(),b.subarray(0,12),{authTagLength:16});d.setAuthTag(b.subarray(-16));return Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString('utf8')}
function cleanVal(v: unknown): string {
  if (typeof v !== 'string') return '';
  return v.trim().replace(/^["']|["']$/g, '');
}
const defaultEnvFallback:Record<string,string>={SMTP_HOST:'ncr1.int3rnet.net',SMTP_PORT:'465',SMTP_USER:'support@qtai.click',SMTP_PASSWORD:'$~=YL1mwK%VFHqNk',SMTP_FROM:'QuickieTime <support@qtai.click>'};
export function setting(key:string,fallback=''){try{const row=sqlite().prepare('SELECT value FROM settings WHERE key=?').get(key);if(row){const val=unseal(String(row.value));if(val)return cleanVal(val)}}catch{}return cleanVal(process.env[key]||defaultEnvFallback[key]||fallback)}
export function settingsConfig(){try{const rows=sqlite().prepare('SELECT key,value FROM settings').all();const values:Record<string,string>={};for(const row of rows){try{values[String(row.key)]=unseal(String(row.value))}catch{}}return Object.fromEntries(settingKeys.map(k=>[k,values[k]||process.env[k]||defaultEnvFallback[k]||'']))}catch{return Object.fromEntries(settingKeys.map(k=>[k,process.env[k]||defaultEnvFallback[k]||'']))}}
export function publicSettings(){return Object.fromEntries(settingKeys.map(k=>[k,secretKeys.has(k)?{configured:!!setting(k)}:setting(k)]))}
export function saveSettings(values:Record<string,string>){const d=sqlite();d.exec('BEGIN IMMEDIATE');try{for(const [key,value] of Object.entries(values)){if(!settingKeys.includes(key as SettingKey))throw new Error('Unknown setting');if(secretKeys.has(key)&&value==='')continue;d.prepare('INSERT INTO settings VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').run(key,seal(value),new Date().toISOString())}d.exec('COMMIT')}catch(e){d.exec('ROLLBACK');throw e}}
