import Link from 'next/link';
import {notFound} from 'next/navigation';
import {articles} from '@/lib/content';
import {PublicPage,StudioCTA} from '@/components/public-page';
import {pageMetadata} from '@/lib/page-seo';
import {siteUrl,jsonLd} from '@/lib/site';
export const dynamicParams=false;
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);return a?pageMetadata(a.title,a.description,'/guides/'+slug):{title:'Not found'}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)notFound();return <PublicPage title={a.title} intro={a.intro} path={'/guides/'+slug} eyebrow={a.category}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,mainEntityOfPage:siteUrl+'/guides/'+slug,author:{'@type':'Organization',name:'QuickieTime editorial',url:siteUrl+'/about'},publisher:{'@id':siteUrl+'/#organization'},inLanguage:'en'})}}/><div className="article-byline">By QuickieTime editorial · Practical product guidance</div><div className="article-layout"><aside className="article-toc"><strong>In this guide</strong>{a.sections.map((s,i)=><a key={s.heading} href={'#step-'+i}>{s.heading}</a>)}<a href="#review-checklist">Review checklist</a><Link href={'/tools/'+a.tool}>About the matching tool →</Link></aside><article className="article-body">{a.sections.map((s,i)=><section id={'step-'+i} key={s.heading}><h2>{s.heading}</h2>{s.body.map(p=><p key={p}>{p}</p>)}{s.example&&<div className="editorial-example"><span>EXAMPLE BRIEF OR WORDING</span><p>{s.example}</p></div>}</section>)}<section id="review-checklist"><h2>Before you use the output</h2><ul>{a.checklist.map(x=><li key={x}>{x}</li>)}</ul></section></article></div><StudioCTA tool={a.tool}/><section className="prose-section"><h2>Keep exploring</h2><ul>{articles.filter(x=>x.slug!==slug).slice(0,3).map(x=><li key={x.slug}><Link href={'/guides/'+x.slug}>{x.title}</Link></li>)}</ul><Link href="/guides" className="text-link">All writing guides →</Link></section></PublicPage>}
