import type { Metadata } from 'next';
import './globals.css';
import {siteUrl,operator,jsonLd} from '@/lib/site';
import {PublicFooter} from '@/components/public-shell';
const description = 'Free AI tagline generator, paragraph rewriter, summarizer and reply writer. Choose your tone, length and formatting. Five daily guest credits; twenty when signed in.';
export const metadata: Metadata = { robots:{index:process.env.SITE_INDEXABLE!=='false'&&!siteUrl.includes('localhost'),follow:true,'max-image-preview':'large','max-snippet':-1}, metadataBase: new URL(siteUrl), title: "QuickieTime — AI Writing Tools. Don't Make a Project Out of It.", description, alternates: { canonical: '/' }, openGraph: { type: 'website', siteName: 'QuickieTime', title: 'QuickieTime — Small effort. Better words.', description, url: '/' }, twitter: { card: 'summary', title: 'QuickieTime — AI writing with personality', description }, icons: { icon: '/favicon.svg' } };
export default function Layout({ children }: {
    children: React.ReactNode;
}) { return <html lang="en"><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'Organization','@id':siteUrl+'/#organization',name:operator,url:siteUrl})}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'WebSite','@id':siteUrl+'/#website',name:'QuickieTime',url:siteUrl+'/',inLanguage:'en'})}}/>{children}<PublicFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebApplication', '@id':siteUrl+'/#app', name: 'QuickieTime', url: siteUrl, applicationCategory: 'BusinessApplication', operatingSystem: 'Web browser', description, offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD', description: 'Limited free daily credits' }, featureList: ['Tagline generator', 'Paragraph rewriter', 'Text summarizer', 'Reply writer', 'Social captions', 'Headlines and subject lines'] }) }}/></body></html>; }
