/* eslint-disable @next/next/no-html-link-for-pages -- Full page navigation preserves the dashboard authentication boundary. */
"use client";
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {MobileIsland} from '@/components/mobile-island';
import {ExamplesCarousel} from '@/components/examples-carousel';
import {ExploreNav} from '@/components/public-shell';
import {useState,useEffect,useRef} from 'react';
import {Zap,History,Moon,Sun,Heart,Sparkles,PenLine,AlignLeft,MessageCircle,Megaphone,Type,Copy} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {StudioSample} from '@/components/studio-sample';
import {starters,readDrafts,nextDraft,draftSchema} from '@/lib/studio';
import {BriefForm} from '@/components/brief-form';
const WritingResult=dynamic(()=>import('@/components/writing-result').then(m=>m.WritingResult),{loading:()=> <p>Loading your draft…</p>});
import {ToolTable} from '@/components/tool-table';
import {type Brief,type Entry,type Result,type Tool,toolCatalog,defaultBrief,inputSchema,validatePlan,isDocument,countOptions,allowedActions} from '@/lib/config';
import {api,local,persist,stash} from '@/lib/client';
import {copyText} from '@/lib/clipboard';
import {analytics} from '@/lib/analytics';
type Usage={authenticated:boolean;remaining:number;limit:number;configured:boolean;paidCredits?:number;dailyRemaining?:number};
const toolIcons={tagline:Sparkles,rewrite:PenLine,summarize:AlignLeft,reply:MessageCircle,social:Megaphone,headlines:Type};
const messages=['Removing the unnecessary…','Finding the right words…','A little less blank page…'];
function restore(value:unknown,auth:boolean):Brief{const parsed=draftSchema.parse(value);if(isDocument(parsed.tool))parsed.count=1;else if(!countOptions(parsed.tool,auth).includes(parsed.count))parsed.count=countOptions(parsed.tool,auth)[0] as Brief['count'];if(parsed.tool!=='tagline'&&['balanced','punchy','descriptive'].includes(parsed.length))parsed.length='standard';parsed.maxWords=Math.min(parsed.maxWords,auth?700:300);if(!['reply','social'].includes(parsed.tool))parsed.maxLines=0;return parsed}
export default function Home(){
const [brief,setBrief]=useState<Brief>(()=>defaultBrief('tagline'));const [entry,setEntry]=useState<Entry|null>(null);const [usage,setUsage]=useState<Usage|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [history,setHistory]=useState<Entry[]>([]);const [favorites,setFavorites]=useState<Result[]>([]);const [historyOpen,setHistoryOpen]=useState(false);const [savedOpen,setSavedOpen]=useState(false);const [historyQuery,setHistoryQuery]=useState('');const [historyLoading,setHistoryLoading]=useState(false);const [historyError,setHistoryError]=useState('');const [projects,setProjects]=useState<string[]>([]);const [dark,setDark]=useState(false);const [message,setMessage]=useState(0);const output=useRef<HTMLElement>(null);const retry=useRef<()=>void>(()=>{});const requestLock=useRef(false);const drafts=useRef<Partial<Record<Tool,Brief>>>({});const toolEntries=useRef<Partial<Record<Tool,Entry|null>>>({});const draftReady=useRef(false);
useEffect(()=>{let active=true;queueMicrotask(()=>{setDark(local('qt-dark',false));const tool=new URLSearchParams(location.search).get('tool') as Tool;try{drafts.current=readDrafts(sessionStorage.getItem('qt-studio-drafts'))}catch{}const selected=toolCatalog.some(t=>t.id===tool)?tool:'tagline';setBrief(nextDraft(selected,drafts.current,''));draftReady.current=true;setHistory(local('qt-history',[]));setFavorites(local('qt-favorites',[]))});analytics.track('homepage_view');api<Usage>('usage').then(async u=>{if(!active)return;setUsage(u);setBrief(b=>restore(b,u.authenticated));const params=new URLSearchParams(location.search);let pending:unknown;try{if(params.has('resume')){const saved=local<{brief:Brief;entry:Entry|null;expires:number}|null>('qt-pending',null);if(saved&&saved.expires>Date.now()){setBrief(restore(saved.brief,u.authenticated));setEntry(u.authenticated?null:saved.entry);localStorage.removeItem('qt-pending')}}else{pending=sessionStorage.getItem('qt-continue');if(pending){const e=JSON.parse(String(pending)) as Entry;setBrief(restore(e.brief,u.authenticated));setEntry(e);sessionStorage.removeItem('qt-continue')}else{const b=sessionStorage.getItem('qt-reuse');if(b){setBrief(restore(JSON.parse(b),u.authenticated));sessionStorage.removeItem('qt-reuse')}}}}catch{toast.error('Could not restore that draft. Your saved history is still available.')}if(u.authenticated){setHistory([]);setFavorites([]);const [f,p]=await Promise.all([api<{results:Result[]}>('favorites'),api<{projects:string[]}>('projects')]);if(active){setFavorites(f.results);setProjects(p.projects)}}}).catch(()=>toast.error('Could not load your account data. Try refreshing.'));return()=>{active=false}},[]);
useEffect(()=>{if(!draftReady.current)return;drafts.current[brief.tool]=brief;try{sessionStorage.setItem('qt-studio-drafts',JSON.stringify(drafts.current))}catch{}},[brief]);
useEffect(()=>{document.documentElement.classList.toggle('dark',dark)},[dark]);
useEffect(()=>{if(!busy)return;const timer=setInterval(()=>setMessage(x=>(x+1)%messages.length),2200);return()=>clearInterval(timer)},[busy]);
useEffect(()=>{if(!historyOpen||!usage?.authenticated)return;let active=true;const timer=setTimeout(()=>{setHistoryLoading(true);setHistoryError('');api<{entries:Entry[]}>('history?q='+encodeURIComponent(historyQuery)).then(h=>{if(active)setHistory(h.entries)}).catch(()=>{if(active)setHistoryError('Could not search history. Close and reopen to retry.')}).finally(()=>{if(active)setHistoryLoading(false)})},250);return()=>{active=false;clearTimeout(timer)}},[historyQuery,historyOpen,usage?.authenticated]);
function choose(tool:Tool){if(requestLock.current||tool===brief.tool)return;drafts.current[brief.tool]=brief;toolEntries.current[brief.tool]=entry;setBrief(restore(nextDraft(tool,drafts.current,brief.project),!!usage?.authenticated));setEntry(toolEntries.current[tool]||null);setError('')}
function tryStarter(){const previous=brief;const sample=starters[brief.tool][0];setBrief({...brief,idea:sample.idea,context:sample.context||''});toast('Example loaded. Generate when ready.',{duration:12000,action:{label:'Undo',onClick:()=>setBrief(previous)}});document.getElementById('idea')?.focus()}
async function copyAll(){if(!entry)return;try{await copyText(entry.results.map(r=>r.text).join('\n\n'));toast.success('All saved results copied.')}catch{toast.error('Could not copy. Try copying one result.')}}
function remember(next:Entry){setEntry(next);setHistory(old=>{const h=[next,...old.filter(x=>x.id!==next.id)].slice(0,50);if(!usage?.authenticated){try{persist('qt-history',h)}catch{toast.error('Browser storage is full. Download your work to keep it.')}}return h})}
async function generate(base=brief,source?:Result,action?:ReturnType<typeof allowedActions>[number]){if(requestLock.current)return;retry.current=()=>void generate(base,source,action);let b:Brief;try{b=inputSchema.parse({...base,avoid:entry?.results.map(r=>r.text.slice(0,300)).slice(0,15)||[],parentId:entry&&usage?.authenticated&&history.some(h=>h.id===entry.id)?entry.id:undefined});const invalid=validatePlan(b,!!usage?.authenticated,action);if(invalid)throw new Error(invalid)}catch(e){setError(e instanceof Error&&e.name!=='ZodError'?e.message:'Add your text and check the settings.');return}retry.current=()=>void generate(b,source,action);requestLock.current=true;setBusy(true);setError('');analytics.track('generation_started');try{const result=await api<{entry:Entry;remaining:number;paidCredits:number;dailyRemaining:number}>(source?'transform':'generate',source?{...b,text:source.text,action}:b);remember(result.entry);setUsage(u=>u?{...u,remaining:result.remaining,paidCredits:result.paidCredits,dailyRemaining:result.dailyRemaining}:u);analytics.track('generation_completed');output.current?.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){if(e&&typeof e==='object'&&'code' in e&&e.code==='RATE_LIMIT')setUsage(u=>u?{...u,remaining:0}:u);setError((e as Error).message);analytics.track('generation_failed')}finally{requestLock.current=false;setBusy(false)}}
function preserve(){try{stash(brief,entry)}catch{toast.error('Could not preserve this draft. Copy your input before signing in.')}}
async function favorite(r:Result){const has=favorites.some(f=>f.id===r.id);try{if(usage?.authenticated)await api(has?'favorites/'+r.id:'favorites',has?undefined:r,has?'DELETE':'POST');const next=has?favorites.filter(f=>f.id!==r.id):[r,...favorites].slice(0,500);setFavorites(next);if(!usage?.authenticated)persist('qt-favorites',next);toast.success(has?'Removed favorite.':'A keeper. Saved.')}catch{toast.error('Could not save this favorite.')}}
async function saveEdit(r:Result,text:string,format:Brief['format']){if(!entry)return;const results=entry.results.map(x=>x.id===r.id?{...x,text}:x);if(usage?.authenticated){const data=await api<{entry:Entry}>('history',{id:entry.id,results,format},'PATCH');remember(data.entry)}else{remember({...entry,id:crypto.randomUUID(),parentId:entry.id,rootId:entry.rootId||entry.id,kind:'edit',brief:{...entry.brief,format},results:results.map(x=>({...x,id:crypto.randomUUID()})),createdAt:new Date().toISOString()})}toast.success('New version saved. No credit used.')}
function openEntry(e:Entry){setEntry(e);try{setBrief(restore(e.brief,!!usage?.authenticated))}catch{setBrief({...defaultBrief('tagline'),idea:e.brief.idea})}setHistoryOpen(false);setTimeout(()=>output.current?.scrollIntoView({behavior:'smooth'}),50)}
const historyResults=usage?.authenticated?history:history.filter(h=>[h.brief.idea,...h.results.map(r=>r.text)].join(' ').toLowerCase().includes(historyQuery.toLowerCase()));
return <><a className="skip-link" href="#writing-studio">Skip to writing tools</a><Toaster position="bottom-center" richColors/><header className="site-header"><Link className="brand" href="/"><span className="brand-icon"><Zap fill="currentColor" size={22}/></span>QuickieTime</Link><nav aria-label="Main navigation"><button onClick={()=>setHistoryOpen(true)}><History size={17}/>History</button><button onClick={()=>setSavedOpen(true)}><Heart size={17}/>Favorites</button><button aria-label={dark?'Use light theme':'Use dark theme'} onClick={()=>{setDark(!dark);try{persist('qt-dark',!dark)}catch{}}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>{usage?.authenticated?<a className="signin" href="/dashboard" target="_self" onClick={preserve}>Dashboard ↗</a>:<Link className="signin" href="/auth?return_to=%2F%3Fresume%3D1" onClick={preserve}>Sign in / Sign up ↗</Link>}</nav></header><ExploreNav/><MobileIsland authenticated={!!usage?.authenticated} onHistory={()=>setHistoryOpen(true)} onPreserve={preserve}/>
<main><section className="studio-intro"><div><span className="intro-kicker"><Sparkles size={15}/> YOUR LITTLE CREATIVE ADVANTAGE</span><h1>Big on personality.<br/><span>Small on effort.</span></h1><p className="intro-description">Six AI writing tools. One less blank page. Make it sharp, warm, witty—or wonderfully weird.</p></div><div className="credit-ticket"><span className="ticket-heading"><Zap size={16} fill="currentColor"/> YOUR DAILY WORD FUEL</span><strong>{usage?.remaining??5}<span> credits available</span></strong><div className="credit-meter" role="progressbar" aria-label="Daily credits remaining" aria-valuenow={usage?.dailyRemaining??usage?.remaining??5} aria-valuemin={0} aria-valuemax={usage?.limit??5}><span style={{width:`${usage?Math.min(100,(usage.dailyRemaining??usage.remaining)/usage.limit*100):100}%`}}/></div><p>{usage?.authenticated?'Let’s make something worth keeping.':'5 as a guest. 20 when you sign in.'}</p><small>{usage?.paidCredits?`${usage.dailyRemaining??0} daily + ${usage.paidCredits} purchased · daily credits used first`:"Resets at midnight UTC · failed requests refunded"}</small></div></section>
<div className="tool-nav" id="writing-studio"><Tabs value={brief.tool} onValueChange={t=>choose(t as Tool)}><TabsList>{toolCatalog.map(t=><TabsTrigger onClick={()=>choose(t.id)} disabled={busy} value={t.id} key={t.id}><span className="tool-tab-icon">{(()=>{const Icon=toolIcons[t.id];return <Icon size={18}/>})()}</span>{({tagline:'Taglines',rewrite:'Rewrite',summarize:'Summarize',reply:'Reply',social:'Captions',headlines:'Headlines'})[t.id]}</TabsTrigger>)}</TabsList></Tabs><label className="mobile-tool-picker">Writing tool<select disabled={busy} value={brief.tool} onChange={e=>choose(e.target.value as Tool)}>{toolCatalog.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>
<div className="workspace studio-workspace" data-tool={brief.tool}><div><BriefForm brief={brief} onChange={setBrief} authenticated={!!usage?.authenticated} busy={busy} remaining={usage?.remaining??null} onSubmit={()=>void generate()} projects={projects}/><p className="allowance">Editing, saving, copying and downloading are free. Briefs stay in this tab when you switch tools.</p>{usage?.remaining===0&&<div className="quota-notice"><h3>{usage.authenticated?'You’ve used today’s credits.':'Five down. More where that came from.'}</h3>{usage.authenticated?<p>Your free allowance resets at midnight UTC. <Link href="/pricing">Get extra credits now →</Link></p>:<><p>Sign in for 20 daily credits and cloud projects. Your current brief will be kept.</p><Link className="primary-button" href="/auth?return_to=%2F%3Fresume%3D1" onClick={preserve}>Sign in / Sign up</Link></>}</div>}{error&&<div className="error" role="alert"><strong>Let’s try that again.</strong><p>{error}</p><button disabled={busy} onClick={()=>retry.current()}>Retry</button></div>}</div>
<section ref={output} className="output studio-output" aria-live="polite" aria-busy={busy}><div className="panel-heading"><span className="step-tag">02 / YOUR {isDocument(brief.tool)?'DRAFT':'IDEAS'}</span><span className="little-note">{entry?'Saved '+(usage?.authenticated?'to your account':'in this browser'):'Room for something good.'}</span></div>{busy?<div className="empty"><span className="loading-pulse"/><h2>{messages[message]}</h2><p>One request, one credit. Any internal repairs are on us.</p></div>:entry?<><div className="output-title">{entry.results.length>1&&<button className="copy-all" onClick={()=>void copyAll()}><Copy size={15}/> Copy all saved results</button>}<h2>{isDocument(entry.brief.tool||'tagline')?'Your next draft.':'A few ways to say it.'}</h2><p>{entry.title||entry.brief.idea.slice(0,100)}</p>{entry.parentId&&<span className="version-label">New version · earlier versions remain in History</span>}</div><div className="results-list">{entry.results.map((r,i)=><WritingResult key={r.id} result={r} index={i} brief={restore(entry.brief,!!usage?.authenticated)} saved={favorites.some(f=>f.id===r.id)} busy={busy||usage?.remaining===0} onFavorite={()=>void favorite(r)} onTransform={a=>void generate(restore(entry.brief,!!usage?.authenticated),r,a)} onSave={(text,format)=>saveEdit(r,text,format)}/>)}</div><button className="another" disabled={busy||usage?.remaining===0} onClick={()=>void generate(restore(entry.brief,!!usage?.authenticated))}>{isDocument(brief.tool)?'Generate another version':'Generate alternatives'} · 1 credit</button></>:<StudioSample tool={brief.tool} onTry={tryStarter}/>}</section></div>
<ExamplesCarousel onTry={(tool,idea,context)=>{if(requestLock.current)return;choose(tool);setBrief({...defaultBrief(tool),idea,context:context||''});document.getElementById('writing-studio')?.scrollIntoView({behavior:'smooth'});toast.success('Example loaded. Generate when ready.')}}/><ToolTable selected={brief.tool} onSelect={t=>{choose(t);document.querySelector('.tool-nav')?.scrollIntoView({behavior:'smooth'})}}/>
<section className="faq"><div><span className="step-tag">QUICK ANSWERS</span><h2>A little less guesswork.</h2></div><div>{[['How do credits work?','Guests get 5 daily credits; signed-in users get 20. A generation or requested AI transformation costs one credit. Failed requests and internal repairs do not. Editing, copying and saving are free. Credits reset at midnight UTC.'],['Why do the tools have different settings?','A tagline needs a short per-idea length; a summary needs a source and detail level; a reply needs context and a channel. Each tool shows only the controls relevant to its task.'],['How much text can I generate?','Longer drafts and caption batches allow up to 300 output words for guests or 700 when signed in. Taglines and headlines use per-idea limits instead. Summaries stay shorter than the source.'],['Is my work public?','No. Guest history stays in your browser. Signed-in work belongs to your account. Your input is sent to our AI provider for generation; avoid passwords and sensitive data.'],['How do formatting and editing work?','Edit the draft for free, preview basic formatting, then copy its full Markdown or WhatsApp syntax. Saving creates a new version so you can return to the earlier draft.'],['Can I publish the output?','Review accuracy and suitability first. Check distinctive brand wording against existing trademarks. AI can generate similar wording for different people.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section></main>
<Dialog open={historyOpen} onOpenChange={setHistoryOpen}><DialogContent className="history-dialog"><DialogTitle>Your previous work</DialogTitle><input className="history-search" aria-label="Search history" value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)} placeholder={usage?.authenticated?'Search all saved work':'Search this browser’s history'}/>{usage?.authenticated&&<Link href="/dashboard">Projects, dates and all results →</Link>}{historyError&&<p role="alert">{historyError}</p>}<div className="history-scroll">{historyLoading?<p>Searching…</p>:historyResults.length?historyResults.map(h=><button className="history-entry" key={h.id} onClick={()=>openEntry(h)}><span>{h.title||h.brief.idea.slice(0,80)}</span><small>{h.brief.tool||'tagline'} · {h.kind||'generation'} · {new Date(h.createdAt).toLocaleDateString()}</small></button>):<p>No matching work yet.</p>}</div></DialogContent></Dialog>
<Dialog open={savedOpen} onOpenChange={setSavedOpen}><DialogContent className="history-dialog"><DialogTitle>Your favorites</DialogTitle><div className="history-scroll">{favorites.length?favorites.map(r=><article className="saved-output" key={r.id}><p className="content-output">{r.text}</p><button onClick={()=>void copyText(r.text).then(()=>toast.success('Copied.')).catch(()=>toast.error('Select the text to copy it.'))}>Copy</button><button onClick={()=>void favorite(r)}>Remove favorite</button></article>):<p>Tap a result’s heart to keep it here.</p>}</div></DialogContent></Dialog>
</>}
