'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
export type Pack={id:string;name:string;description:string;credits:number;amount:number;currency:string;providers:string[]};
type Order={id:string;plan_name:string;amount:number;currency:string;status:string;credits:number;created_at:string;provider:string;refunded_amount:number;checkout_url?:string};
const money=(amount:number,currency:string)=>new Intl.NumberFormat('en',{style:'currency',currency}).format(amount/100);
async function billing<T>(action:string,body?:unknown){const r=await fetch('/api/billing/'+action,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'Could not load billing.');return d as T}
export function CreditPacks({packs}:{packs:Pack[]}){return <><div className="paid-pack-heading"><span className="intro-kicker">MORE ROOM FOR GOOD IDEAS</span><h2>Need a little extra?</h2><p>One payment. Extra credits. No recurring subscription.</p></div>{packs.length?<div className="pack-grid">{packs.map(p=><article className="pack-card" key={p.id}><span className="category-pill">CREDIT PACK</span><h3>{p.name}</h3><strong>{money(p.amount,p.currency)}</strong><p>{p.description}</p><b>{p.credits.toLocaleString()} generation credits</b><ul><li>Use after your free daily allowance</li><li>No expiry or automatic renewal</li><li>All six tools and account features</li></ul><Link className="primary-button" href={'/checkout?plan='+p.id}>Choose this pack →</Link></article>)}</div>:<p className="admin-note">Extra credit packs are not on sale yet. You can still use 20 free daily credits with an account.</p>}</>}
export function Checkout(){const [packs,setPacks]=useState<Pack[]>([]),[planId,setPlanId]=useState(''),[provider,setProvider]=useState(''),[coupon,setCoupon]=useState(''),[order,setOrder]=useState<Order|null>(null),[orderId,setOrderId]=useState(''),[signedIn,setSignedIn]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[requestKey,setRequestKey]=useState('');
useEffect(()=>{const p=new URLSearchParams(location.search);queueMicrotask(()=>{setPlanId(p.get('plan')||'');setOrderId(p.get('order')||'');setRequestKey(crypto.randomUUID())});void Promise.all([billing<{plans:Pack[]}>('plans'),fetch('/api/usage').then(r=>r.json())]).then(([b,u])=>{setPacks(b.plans);setSignedIn(u.authenticated);if(p.get('order')&&u.authenticated)return billing<{orders:Order[]}>('orders').then(x=>setOrder(x.orders.find(o=>o.id===p.get('order'))||null))}).catch(e=>setError(e.message)).finally(()=>setReady(true))},[]);
const pack=packs.find(p=>p.id===planId);async function pay(){if(!pack)return;setBusy(true);setError('');try{const d=await billing<{url:string}>('checkout',{planId,provider:provider||pack.providers[0],coupon,requestKey});window.location.assign(d.url)}catch(e){setError((e as Error).message);setBusy(false)}}
async function verify(){setBusy(true);setError('');try{const d=await billing<{order:Order}>('verify',{id:orderId,capture:true});setOrder(d.order);if(d.order.status==='pending')setError('Payment has not been confirmed yet. Wait a moment, then check again.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <section className="checkout-card">{!ready?<p role="status">Loading checkout…</p>:!signedIn?<><h2>Keep your credits in your account.</h2><p>Sign in before purchasing so your credits reach the right place.</p><Link className="primary-button" href={'/auth?return_to='+encodeURIComponent('/checkout?'+(orderId?'order='+orderId:'plan='+planId))}>Sign in to continue</Link></>:orderId?<><span className="category-pill">PAYMENT STATUS</span><h2>{order?.status==='paid'?'Your credits are ready.':order?.status==='refunded'?'This order was refunded.':'Confirm your payment'}</h2><p>{order?.plan_name} · {order?money(order.amount,order.currency):orderId}</p>{order?.status==='paid'?<><p>{order.credits} credits were added once to your account.</p><Link className="primary-button" href="/">Start creating →</Link></>:<><p>Returning here does not itself confirm payment. We verify the amount and status directly with your payment provider.</p><button disabled={busy} className="primary-button" onClick={()=>void verify()}>{busy?'Verifying…':'Verify / complete payment'}</button></>}<Link href="/billing">View billing history</Link></>:pack?<><span className="category-pill">ONE-TIME PURCHASE</span><h2>{pack.name}</h2><strong className="checkout-price">{money(pack.amount,pack.currency)}</strong><p>{pack.credits} credits · no expiry · no recurring charge</p><p>{pack.description}</p><label>Coupon code (optional)<input value={coupon} maxLength={32} onChange={e=>{setCoupon(e.target.value.toUpperCase());setRequestKey(crypto.randomUUID())}} placeholder="Enter your code"/></label><label>Payment method<select value={provider||pack.providers[0]||''} onChange={e=>{setProvider(e.target.value);setRequestKey(crypto.randomUUID())}}>{pack.providers.map(p=><option key={p} value={p}>{({stripe:'Stripe · card & supported wallets',paypal:'PayPal',razorpay:'Razorpay · UPI, cards & supported methods'})[p]}</option>)}</select></label>{!pack.providers.length&&<p role="status">Payment methods are not available for this pack yet. Please contact support.</p>}<p className="setting-hint">Your final total, including any coupon discount, is shown on the secure provider page before you pay. Card and bank details are handled by your payment provider.</p><button className="primary-button" disabled={busy||!pack.providers.length} onClick={()=>void pay()}>{busy?'Opening secure checkout…':'Continue to secure checkout →'}</button><p className="setting-hint">Purchases follow our <Link href="/terms">terms</Link> and <Link href="/refund-policy">refund policy</Link>. Available methods depend on the provider, country and currency.</p></>:<><h2>Choose a credit pack first.</h2><Link href="/pricing" className="primary-button">See plans & credits</Link></>}{error&&<p className="error" role="alert">{error}</p>}</section>
}
export function BillingHistory(){const [orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(''),[ready,setReady]=useState(false);useEffect(()=>{void billing<{orders:Order[]}>('orders').then(d=>setOrders(d.orders)).catch(e=>setError(e.message)).finally(()=>setReady(true))},[]);return <>{error&&<p role="alert" className="error">{error} <Link href="/auth?return_to=%2Fbilling">Sign in</Link></p>}<Link className="primary-button" href="/pricing">Get more credits</Link><div className="admin-table-wrap"><table><thead><tr><th>Pack</th><th>Total</th><th>Status</th><th>Order</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.plan_name}<small>{new Date(o.created_at).toLocaleString()}</small></td><td>{money(o.amount,o.currency)}{o.refunded_amount>0&&<small>Refunded: {money(o.refunded_amount,o.currency)}</small>}</td><td>{o.status}</td><td><Link href={'/checkout?order='+o.id}>View order</Link></td></tr>)}</tbody></table></div>{ready&&!orders.length&&!error&&<p>No purchases yet. Your free daily allowance remains available.</p>}</>}
