"use client";
import {useState} from 'react';
import {type Brief,toolCatalog,tones,creativeTool,isDocument,countOptions,inputLimit} from '@/lib/config';
import {starters} from '@/lib/studio';
import {toast} from 'sonner';
import {Sparkles,ArrowUpRight} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
export function BriefForm({brief:b,onChange,authenticated,busy,remaining,onSubmit,projects,isByok,byokProvider}:{brief:Brief;onChange:(b:Brief)=>void;authenticated:boolean;busy:boolean;remaining:number|null;onSubmit:()=>void;projects:string[];isByok?:boolean;byokProvider?:string}){
const [previous,setPrevious]=useState<Brief|null>(null);const set=(patch:Partial<Brief>)=>onChange({...b,...patch});function loadSample(index:number){const old=b;setPrevious(old);const sample=starters[b.tool][index];set({idea:sample.idea,context:sample.context||''});toast('Example loaded. No credit used.')}const card=['tagline','headlines'].includes(b.tool);const cap=authenticated?700:300;
const label={tagline:'What needs a tagline?',rewrite:'Paste your original text',summarize:'Paste the text to summarize',reply:'Paste the message you received',social:'What are you posting about?',headlines:'What is the content or offer?'}[b.tool];
const options=creativeTool(b.tool)?tones.filter(t=>!['Neutral','Polite'].includes(t)):['Clear','Professional','Warm','Polite','Minimal'] as const;
const canSubmit = !busy && (isByok || remaining !== 0);
return <section className="generator"><div className="panel-heading"><span className="step-tag">01 / THE BRIEF</span><span className="little-note">{isByok ? `BYOK Active: ${byokProvider || 'Custom'} (Unlimited)` : b.tool==='summarize'?'Facts first. Fluff last.':'A little direction goes a long way.'}</span></div>
<div className="micro-task-disclaimer" style={{display:'flex',alignItems:'center',gap:'8px',padding:'10px 14px',marginBottom:'14px',borderRadius:'10px',background:'var(--surface-muted, rgba(255,255,255,0.04))',border:'1px solid var(--border, rgba(255,255,255,0.1))',fontSize:'12px',color:'var(--foreground-muted, #a1a1aa)',lineHeight:'1.4'}} role="note">
<span style={{fontSize:'16px'}}>⚡</span>
<span><strong>Quickie Micro-Tasks:</strong> Inputs have tight character limits by design to ensure sub-second AI speed, zero timeouts, and minimal token cost. For long essays or back-and-forth chat, standard chat tools are better suited.</span>
</div>
<form onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(canSubmit)e.currentTarget.requestSubmit()}}} onSubmit={e=>{e.preventDefault();onSubmit()}}><fieldset disabled={busy} className="brief-fields"><h2><label htmlFor="idea">{label}</label></h2><textarea id="idea" className="brief-input" value={b.idea} maxLength={inputLimit(b.tool,authenticated)} onChange={e=>set({idea:e.target.value})} placeholder={toolCatalog.find(t=>t.id===b.tool)!.example} required minLength={3}/><div className="input-meta"><span className="starter-caption">Need a spark?</span><span>{b.idea.length.toLocaleString()} / {inputLimit(b.tool,authenticated).toLocaleString()}</span></div>
<div className="starter-chips">{starters[b.tool].map((sample,i)=><button type="button" key={sample.label} onClick={()=>loadSample(i)}><Sparkles size={12}/>{sample.label}</button>)}</div>{previous&&previous.tool===b.tool&&<button className="undo-example" type="button" onClick={()=>{onChange(previous);setPrevious(null)}}>Undo example</button>}<label className="form-label">{b.tool==='reply'?'Verified facts & what should happen next':b.tool==='summarize'?'Focus on (optional)':b.tool==='tagline'?'What makes it different? (optional)':'Context or instructions (optional)'}<textarea className="brief-context" value={b.context} maxLength={400} onChange={e=>set({context:e.target.value})} placeholder={b.tool==='reply'?'What can you confirm? What should the recipient do next?':'What must stay, what to avoid, or what matters most…'}/><div style={{display:'flex',justifyContent:'flex-end',fontSize:'11px',opacity:0.7,marginTop:'2px'}}><span>{b.context.length} / 400</span></div></label>
<div className="writing-settings">{b.tool!=='summarize'&&<label>Audience<input value={b.audience} maxLength={120} onChange={e=>set({audience:e.target.value})} placeholder="Who is this for?"/></label>}{['rewrite','social'].includes(b.tool)&&<label>{b.tool==='rewrite'?'Purpose':'Objective'}<input value={b.purpose} maxLength={150} onChange={e=>set({purpose:e.target.value})} placeholder={b.tool==='rewrite'?'Explain, persuade, clarify…':'Announce, invite, drive a click…'}/></label>}{b.tool==='reply'&&<label>Reply channel<select value={b.channel} onChange={e=>set({channel:e.target.value as Brief['channel']})}><option value="email">Email</option><option value="support">Support ticket</option><option value="chat">Chat message</option></select></label>}{b.tool==='social'&&<label>Platform<select value={b.channel} onChange={e=>set({channel:e.target.value as Brief['channel']})}><option value="instagram">Instagram</option><option value="linkedin">LinkedIn</option><option value="x">X · 280 characters/caption</option></select></label>}{b.tool==='headlines'&&<label>Type<select value={b.channel} onChange={e=>set({channel:e.target.value as Brief['channel']})}><option value="headline">Headline · up to 110 characters</option><option value="subject">Email subject · up to 70 characters</option></select></label>}
{b.tool==='tagline'&&<label>Tagline length<select value={b.length} onChange={e=>set({length:e.target.value as Brief['length']})}><option value="punchy">Punchy · up to 5 words each</option><option value="balanced">Balanced · up to 10 words each</option><option value="descriptive">Descriptive · up to 16 words each</option></select></label>}
{!isDocument(b.tool)&&<label>Number of {b.tool==='social'?'captions':'ideas'}<select value={b.count} onChange={e=>set({count:Number(e.target.value) as Brief['count']})}>{countOptions(b.tool,authenticated).map(n=><option value={n} key={n}>{n} {b.tool==='social'?'captions':'ideas'}</option>)}</select></label>}
{!card&&<><label>{b.tool==='summarize'?'Detail level':'Output length'}<select value={b.length} onChange={e=>set({length:e.target.value as Brief['length']})}><option value="short">{b.tool==='summarize'?'Brief':'Short'}</option><option value="standard">{b.tool==='summarize'?'Balanced':'Standard'}</option><option value="detailed">Detailed</option><option value="custom">Custom word target</option></select></label>{b.length==='custom'&&<label>Maximum words (total)<input type="number" min={20} max={cap} value={b.maxWords} onChange={e=>set({maxWords:Number(e.target.value)})}/></label>}
<label>Output format<select value={b.format} onChange={e=>set({format:e.target.value as Brief['format']})}><option value="plain">Plain text</option><option value="markdown">Markdown</option><option value="whatsapp">WhatsApp</option></select></label></>}
{b.tool==='rewrite'&&<label>Compared with the original<select value={b.rewriteSize} onChange={e=>set({rewriteSize:e.target.value as Brief['rewriteSize']})}><option value="shorter">Shorter</option><option value="similar">Similar length</option><option value="longer">Expand slightly</option></select></label>}
{b.tool==='summarize'&&<label>Structure<select value={b.structure} onChange={e=>set({structure:e.target.value as Brief['structure']})}><option value="paragraph">Paragraph</option><option value="bullets">Bullet points</option></select></label>}
{authenticated&&<label>Project (optional)<input value={b.project} maxLength={80} list="project-options" onChange={e=>set({project:e.target.value})}/><datalist id="project-options">{projects.map(p=><option key={p} value={p}/>)}</datalist></label>}</div>
{b.tool==='social'&&<label className="check-label"><input type="checkbox" checked={b.hashtags} onChange={e=>set({hashtags:e.target.checked})}/> Include relevant hashtags</label>}
{b.tool!=='summarize'&&<details className="tone-options" open={!isDocument(b.tool)}><summary>Tone · {b.tones.join(' + ')}</summary><div className="tones">{options.map(t=><button type="button" key={t} aria-pressed={b.tones.includes(t)} className={b.tones.includes(t)?'selected':''} onClick={()=>set({tones:b.tones.includes(t)?b.tones.length>1?b.tones.filter(x=>x!==t):b.tones:b.tones.length<4?[...b.tones,t]:b.tones})}>{t}</button>)}</div></details>}
{creativeTool(b.tool)&&<div className="chaos-field"><div className="field-title"><h3>Creative freedom</h3><span>{b.chaos<=3?'Grounded':b.chaos<=6?'Playful':'Adventurous'}</span></div><Slider aria-label="Creative freedom" min={1} max={10} step={1} value={[b.chaos]} onValueChange={([chaos])=>set({chaos})}/><div className="slider-labels"><span>Keep it practical</span><span>Surprise me</span></div></div>}
{['reply','social'].includes(b.tool)&&<details className="advanced-options"><summary>Advanced: explicit line limit</summary><label className="form-label">Maximum lines · 0 means automatic<input type="number" min={0} max={authenticated?50:20} value={b.maxLines} onChange={e=>set({maxLines:Number(e.target.value)})}/></label><p className="setting-hint">Optional line breaks, not wrapping on your screen. Applies across the entire response.</p></details>}
<p className="setting-hint">{card?'Each idea has its own short length limit.':b.tool==='summarize'?'Summaries stay shorter than your source.':`Up to ${cap} words across the response.`} {b.tool==='rewrite'?'The original length and your preference guide the result.':''}</p>
</fieldset><button className="primary-button generate-main" type="submit" disabled={!canSubmit}><Sparkles size={18}/>{busy?'Working on your words…':isByok?`Generate ${b.tool==='tagline'?'taglines':b.tool==='headlines'?'ideas':b.tool==='social'?'captions':b.tool==='reply'?'reply':b.tool==='summarize'?'summary':'rewrite'} · BYOK Unlimited`: `Generate ${b.tool==='tagline'?'taglines':b.tool==='headlines'?'ideas':b.tool==='social'?'captions':b.tool==='reply'?'reply':b.tool==='summarize'?'summary':'rewrite'} · 1 credit`}<ArrowUpRight size={19}/></button><p className="keyboard-hint"><kbd>Ctrl</kbd> / <kbd>⌘</kbd> + <kbd>Enter</kbd> to generate</p></form></section>}

