export type Article={slug:string;title:string;description:string;tool:string;category:string;intro:string;sections:{heading:string;body:string[];example?:string}[];checklist:string[]};
export const articles:Article[]=[
{slug:'write-a-memorable-tagline',title:'How to write a memorable tagline',description:'Turn a product difference into a short, specific tagline. A practical brief, examples and a checklist for choosing the strongest idea.',tool:'tagline',category:'Brand writing',intro:'A good tagline gives people one useful thing to remember. It does not need to explain your entire business, list every feature or sound like a mission statement. Start with a specific difference, then make that difference easy to repeat.',sections:[
{heading:'Find a difference worth saying',body:['Write down what you offer, who it helps and what changes for that person. “Coffee for everyone” is broad. “Coffee for students who study after midnight” gives the writing somewhere to go. Availability, convenience, craftsmanship or a distinctive attitude can each become a useful angle.','Choose one angle for the first batch. If every result tries to mention price, quality, speed and service, the output is likely to feel crowded.'],example:'Business: a student coffee shop. Difference: open until 3 AM. Audience: people studying late. Tone: clever. Length: punchy.'},
{heading:'Compare ideas, not just wording',body:['Generate a small batch and look for different approaches: a direct benefit, an unexpected contrast or a phrase with a little wordplay. Five versions of the same sentence offer less choice than three clearly different concepts.','“Coffee after curfew” and “Your 3 AM study buddy” emphasize different ideas. Neither example proves legal availability or guarantees that the wording is original.']},
{heading:'Choose a length that fits the placement',body:['Punchy taglines work well where space is tight. A more descriptive line can help a new visitor understand an unfamiliar product. QuickieTime offers limits of 5, 10 or 16 words per idea so a tagline does not become a paragraph.','Read the strongest candidates aloud. Put them beside the brand name and on the actual page or packaging. A phrase that looks clever in a list may be awkward in the place where it will be used.']},
{heading:'Edit and check before publishing',body:['Remove generic words that any competitor could use. Avoid promises you cannot substantiate. A delivery service should not promise instant delivery if it cannot provide it.','Check important brand wording against existing businesses and trademarks. Keep the original brief and the alternatives you considered in a project so the next round starts with context.']}],checklist:['One clear idea','Easy to say aloud','Fits the actual placement','No unsupported promise','Brand and trademark checks completed']},
{slug:'rewrite-without-changing-meaning',title:'Rewrite a paragraph without changing its meaning',description:'Improve clarity while preserving facts, dates and commitments. Learn how to brief a paragraph rewriter and review the result.',tool:'rewrite',category:'Clear communication',intro:'Rewriting should make the reader’s job easier. It should not quietly change a deadline, soften an obligation or introduce an offer that was never approved. Separate the facts that must stay from the wording that can change.',sections:[
{heading:'Mark the non-negotiable facts',body:['Before you rewrite, identify names, dates, amounts, conditions and promises. Tell the writer which details must stay. If an announcement says the existing price remains until renewal, “your price will never change” is not an acceptable rewrite.','Paste the full relevant paragraph rather than an isolated sentence when the surrounding context changes its meaning.']},
{heading:'Name the audience and the job',body:['A support reply, a product description and an internal update have different priorities. Tell the rewriter who will read the text and what they need to understand or do. “Make this professional” is less useful than “Explain the renewal change clearly to an existing customer.”'],example:'Audience: existing customers. Purpose: explain a plan update. Tone: clear and warm. Keep: current price stays until the next renewal.'},
{heading:'Choose a realistic length',body:['Shorter is useful when the draft repeats itself. Similar length helps when the original already contains the necessary detail. A slight expansion can explain a confusing idea, but it should not invent missing facts.','Word targets are ceilings, not a reason to pad the draft. If the source is brief, the result may be much shorter than the selected plan limit.']},
{heading:'Review the difference',body:['Compare the original and the rewrite side by side. Check dates, amounts, conditions and the strength of every promise. Read the rewritten paragraph as someone who has not seen the original.','Use free editing to fix small phrasing issues. Save a new version when you want to retain the earlier draft, rather than spending another AI credit on a punctuation change.']}],checklist:['Facts unchanged','Audience is clear','One main point per paragraph','No unnecessary jargon','Next step is unambiguous']},
{slug:'summarize-meeting-notes',title:'Turn meeting notes into an accurate summary',description:'Extract decisions, owners and deadlines from meeting notes without inventing actions. Choose a useful level of detail and check the source.',tool:'summarize',category:'Everyday productivity',intro:'Meeting summaries are useful when they make decisions easier to find. They become risky when suggestions turn into commitments or unnamed tasks receive invented owners. Keep the source available while you review the summary.',sections:[
{heading:'Start with the actual notes',body:['Paste the relevant notes as text. QuickieTime does not open links or fetch documents from a URL. Remove unrelated chatter and sensitive information before submitting the source.','Incomplete notes produce incomplete summaries. If a deadline was discussed but never agreed, say that explicitly in the source.']},
{heading:'Separate decisions from discussion',body:['Use the focus field to ask for confirmed decisions, named owners and explicit deadlines. The summary should not fill gaps just because a tidy action list looks more useful.'],example:'Focus on confirmed launch decisions and explicit deadlines. Mark unresolved questions as unresolved. Do not assign an owner unless the notes name one.'},
{heading:'Pick a structure for the reader',body:['A short paragraph works well for an update at the top of an email. Bullet points make several decisions easier to scan. Brief detail is useful for a quick recap; detailed summaries can retain supporting context.','The summary should stay shorter than the source. If you need a complete record, keep the notes alongside the summary rather than asking the summary to replace them.']},
{heading:'Audit the result against the notes',body:['Check each decision and deadline. Watch for certainty changes: “might launch Friday” is different from “launches Friday.” Ensure disagreements and unresolved items have not disappeared.','A summary is a reading aid. It does not establish that a meeting participant approved an action, and it should not be treated as a substitute for a formal record when one is required.']}],checklist:['Only source-supported claims','Owners actually named','Deadlines explicitly agreed','Unresolved items preserved','Original notes retained']},
{slug:'write-helpful-customer-replies',title:'Write customer replies that are clear and useful',description:'A practical structure for support replies: acknowledge the issue, share verified facts and explain the next step without unsupported promises.',tool:'reply',category:'Customer support',intro:'The most useful support reply reduces uncertainty. The customer should understand what you know, what you still need to check and what happens next. A friendly tone helps, but it cannot replace an accurate answer.',sections:[
{heading:'Acknowledge the specific issue',body:['Begin with the problem the customer actually reported. Avoid opening with a long apology or a generic paragraph that could belong in any ticket. If payment failed, talk about that payment attempt before explaining unrelated billing features.']},
{heading:'Give the writer verified facts',body:['Paste the customer’s message as the source. Use the facts field for the checks you have completed and any approved next steps. The AI cannot inspect orders, payments, server logs or account settings by itself.','Never include passwords, private keys or full payment details. Replace information that is unnecessary for the wording with a neutral description.'],example:'Verified: no successful payment is visible in the order. Next step: ask for the transaction reference and error message. Do not claim that a refund has been initiated.'},
{heading:'Choose the channel and tone',body:['Email may need a greeting and closing. A chat response should usually be shorter. Support tickets benefit from clearly separated observations and instructions.','Use clear and polite as a starting point. Humor that works in a tagline can feel dismissive when someone is reporting a service problem.']},
{heading:'Finish with a concrete next step',body:['Ask for the smallest set of information needed to move the case forward. If you need a screenshot, specify what it should show and remind the customer to hide sensitive details.','Before sending, verify every claim about actions taken, timelines, credits and refunds. Keep “we will investigate” distinct from “we have fixed it.”']}],checklist:['Issue acknowledged','Verified facts separated from assumptions','No invented resolution','Necessary next step only','Tone fits the customer’s situation']},
{slug:'markdown-vs-whatsapp-formatting',title:'Markdown vs WhatsApp formatting: what to copy',description:'Understand bold, emphasis and lists in Markdown and WhatsApp. Choose the destination format and preview your draft before sending.',tool:'rewrite',category:'Formatting',intro:'Formatting should make the message easier to scan in the app where it will be read. Copying the same markup everywhere can leave visible punctuation instead of the emphasis you intended.',sections:[
{heading:'Choose the destination first',body:['Use plain text when you need maximum compatibility. Choose Markdown for editors that support it. Choose WhatsApp formatting for messages that use its supported text markers. Different destinations may render a subset of the syntax.','QuickieTime’s preview supports common emphasis, headings and lists. It is a basic preview, not a complete emulation of every publishing platform.']},
{heading:'Understand the common markers',body:['Markdown typically uses double asterisks for bold. WhatsApp uses a single asterisk on each side. Underscores can mark italic text. A heading marker in Markdown should not be assumed to become a heading in WhatsApp.'],example:'Markdown: **Important update**\nWhatsApp: *Important update*\nPlain text: Important update'},
{heading:'Keep structure simple',body:['Short paragraphs and simple lists usually transfer more reliably than tables, nested lists or complex layouts. Use emphasis to highlight a deadline or action, not every sentence.','For a customer reply, put the requested next step on its own line. Avoid decorative formatting that makes the message harder to skim on a phone.']},
{heading:'Preview in the receiving app',body:['The copy button preserves the actual formatting markers. Paste into your destination and inspect the result before publishing or sending. Platform-specific rendering can differ from the basic preview.','Changing format, manually editing and copying do not use an AI credit. Save a new version if you want to keep both the original and the reformatted draft.']}],checklist:['Destination format selected','Formatting markers correct','Simple readable structure','Pasted output checked','Important details still intact']},
{slug:'write-honest-headlines-and-subject-lines',title:'Write headlines people can trust',description:'Create concise headlines and email subject lines that describe the content accurately. Compare useful angles without clickbait or false urgency.',tool:'headlines',category:'Content marketing',intro:'A headline makes a promise about what comes next. A strong hook helps the right reader recognize relevant content; an exaggerated hook creates disappointment. Start with the actual subject rather than a vague request for something catchy.',sections:[
{heading:'Describe the content behind the headline',body:['Give the writer the topic, audience and genuine takeaway. If an article explains three small WordPress improvements, avoid asking for headlines that imply a complete transformation or a guaranteed performance result.'],example:'Article: three ways to improve WordPress loading speed without installing new plugins. Audience: small business owners. Tone: clear with a little personality.'},
{heading:'Distinguish page titles from email subjects',body:['An article headline can explain more context. An email subject often needs to work in a narrow inbox column. QuickieTime keeps headline alternatives within 110 characters and subject lines within 70 characters.','These are product limits, not promises about how many characters every search engine or email app will display. Test the actual layout.']},
{heading:'Compare useful angles',body:['Try a direct benefit, a clear question and a specific practical takeaway. Compare whether each candidate matches the article and helps the intended audience.','Avoid false deadlines, invented statistics and outcomes you cannot substantiate. A subject line should not pretend to be a personal reply when it is a campaign email.']},
{heading:'Improve using actual response data',body:['Once you publish, use the reporting available in your email or website tools to understand whether the headline attracts the right readers. Keep the content and audience comparable when evaluating changes.','Clicks alone do not establish success. A headline that attracts the wrong audience may perform poorly after the click, even if it initially looks effective.']}],checklist:['Matches the actual content','Clear to the intended audience','No invented claim or urgency','Fits its placement','Success measured beyond clicks']}
];
export const useCases=[
{slug:'small-business',title:'AI writing for small businesses',description:'Create product copy, brand taglines and customer updates with a brief that reflects what your business actually offers.',tools:['tagline','rewrite','social'],intro:'A small business needs consistent words in many places: its home page, product descriptions, announcements and social posts. QuickieTime helps produce a first draft while you remain responsible for the facts and final voice.',steps:[['Start with a small brand brief','Record your audience, the offer, the main difference and words you prefer to avoid. Save related generations in one project so each new piece has context.'],['Create one piece for one job','Use Taglines for a short brand line, Rewrite for an existing product paragraph and Captions for a social announcement. Each has different controls because the placements need different outputs.'],['Keep offers consistent','Check prices, opening hours, delivery areas and conditions against your actual business information. A catchy line should not create a promise your team cannot keep.']],example:'We sell handmade ceramic mugs. Each one is slightly different. Audience: people buying thoughtful gifts. Tone: warm and minimal. Avoid claiming that every item is identical.'},
{slug:'customer-support',title:'AI writing for customer support teams',description:'Draft clearer customer replies using verified facts, appropriate tone and a concrete next step.',tools:['reply','rewrite','summarize'],intro:'Support writing works best when it is specific, accurate and easy to act on. Use AI to shape verified information into a helpful reply, then have a person check it before sending.',steps:[['Gather the relevant facts','Review the ticket and your own systems first. QuickieTime does not access accounts, logs or billing systems. Put only verified observations into the context field.'],['Draft for the channel','Choose a support ticket, email or chat response. State the customer’s issue, what you know and the next action. Use shorter output when the request is straightforward.'],['Review every commitment','Check claims about fixes, refunds and response times. Save a revised version for the current case; avoid copying case-specific facts into unrelated tickets.']],example:'Customer reports an error during checkout. We need the error message and transaction reference to investigate. We have not confirmed a successful charge. Use a clear, polite tone.'},
{slug:'content-creators',title:'AI writing for content creators',description:'Explore captions, headlines and concise rewrites while keeping your content accurate and recognizably yours.',tools:['social','headlines','rewrite'],intro:'A useful writing assistant gives you angles to consider. It should not flatten every post into the same voice. Bring your own topic, audience and point of view, then use the alternatives as material to edit.',steps:[['Name the real point of the post','Explain the announcement, lesson or story rather than asking for a generic engaging caption. The more concrete the subject, the easier it is to produce useful alternatives.'],['Match the platform','Choose Instagram, LinkedIn or X for captions. X captions are limited to 280 characters each. Decide whether hashtags actually help the post before enabling them.'],['Make the final wording yours','Compare the drafts, remove clichés and add details only you can verify. Copy or download the result; QuickieTime does not publish to your social accounts.']],example:'Behind-the-scenes post about hand-packing the first 30 orders in our studio. Objective: thank early customers. Tone: warm and playful. No discount offer.'},
{slug:'students-and-professionals',title:'AI writing for everyday notes and communication',description:'Summarize notes, clarify rough paragraphs and draft routine messages while checking the source and keeping your own judgment.',tools:['summarize','rewrite','reply'],intro:'Long notes and rough first drafts can hide the useful part. QuickieTime helps you find a clearer structure for everyday reading and communication. It does not replace learning, independent judgment or any rules that apply to your work.',steps:[['Use the source material','Paste your notes or original paragraph. The summarizer works with supplied text, not live research. It cannot verify facts against outside sources.'],['Choose the smallest useful output','Use a brief summary for a recap, bullets for several decisions or a similar-length rewrite when the details matter. Keep the original alongside the draft.'],['Check before relying on it','Review conclusions, quotes and dates against the source. Follow your school or workplace’s AI policy, and do not submit private or confidential material without permission.']],example:'Summarize these meeting notes into bullet points. Include only decisions, named owners and explicit deadlines. Keep unresolved questions separate.'}
];
export const faqItems=[
['What is QuickieTime?','QuickieTime is a collection of six AI writing tools: tagline generation, paragraph rewriting, text summarization, reply drafting, social captions, and headlines or email subject lines.'],
['Can I use it without an account?','Yes. Guests receive 5 daily generation credits. Their history and favorites are stored in the current browser. Sign in with a verified email for 20 daily credits and account-based saved work.'],
['When do credits reset?','Daily credits reset at midnight UTC. One generation or requested AI transformation costs one credit. Failed requests are refunded; an internal output repair does not cost another credit.'],
['What can I do for free after generating?','Editing, basic format conversion, copying, downloading and saving an edited version do not use an AI credit. Asking AI for a new draft or transformation does.'],
['How long can the output be?','Long drafts and caption batches allow up to 300 words for guests or 700 when signed in. Taglines use 5, 10 or 16 words per idea. Headlines allow up to 110 characters; email subjects allow up to 70. X captions allow up to 280 characters each.'],
['Can the summarizer open a URL or file?','No. Paste the relevant source text. Guest summaries accept up to 12,000 input characters; signed-in summaries accept up to 24,000. Summaries stay shorter than the source.'],
['How do I organize my saved work?','Signed-in users can create projects, move work between projects, search their complete history and filter by tool, project or date. Edits create new versions while retaining the earlier content.'],
['Is generated content public?','No public gallery of user generations exists. Guest work stays in the browser; account work is stored privately. Input is sent to the configured AI provider to produce a response. Read the Privacy policy for details.'],
['Does QuickieTime publish or send content for me?','No. It drafts text. Review, copy or download the result and use your own publishing or communication tools.'],
['Are the examples real customer results?','Public examples are editorial illustrations, clearly labeled. They are not testimonials, usage statistics or promises of identical output.'],
['Will the output be unique or factually correct?','That is not guaranteed. AI can make errors or produce similar wording for different people. Check accuracy, rights and suitability before using a draft.'],
['Can I export or delete my account?','Yes. Account settings offers a JSON export of your account work and permanent deletion of saved content and active sessions. Browser-local guest data can be removed through browser storage controls.']
];
