import {toolCatalog,type Tool} from './config';
import {siteUrl} from './site';
export {siteUrl};
export const toolSeo:Record<Tool,{title:string;description:string;limit:string;input:string;bestFor:string}>={
 tagline:{title:'Free AI Tagline & Slogan Generator',description:'Create short, memorable taglines for your business, product or event. Choose a tone, 3–5 ideas and punchy, balanced or descriptive length. Try free.',limit:'5, 10 or 16 words per idea',input:'Describe your product and its difference',bestFor:'Brand slogans, products and events'},
 rewrite:{title:'Free AI Paragraph Rewriter',description:'Rewrite paragraphs with your audience, purpose and tone in mind. Choose shorter, similar or expanded text, then edit and copy in plain text or Markdown.',limit:'Up to 300 guest / 700 signed-in words',input:'Paste the original paragraph',bestFor:'Announcements, product copy and emails'},
 summarize:{title:'Free AI Text Summarizer',description:'Summarize pasted text into a neutral paragraph or bullet points. Choose brief, balanced or detailed summaries and preserve the source’s key facts.',limit:'Shorter than your source',input:'Up to 12,000 guest / 24,000 signed-in characters',bestFor:'Meeting notes, updates and long passages'},
 reply:{title:'Free AI Email & Customer Reply Writer',description:'Draft an email, support response or chat reply using verified facts and your preferred tone. Edit for free and copy with WhatsApp or Markdown formatting.',limit:'Up to 300 guest / 700 signed-in words',input:'Paste the message and verified facts',bestFor:'Customer support, emails and follow-ups'},
 social:{title:'Free AI Social Media Caption Generator',description:'Write Instagram, LinkedIn or X captions with an audience, objective and optional hashtags. Compare alternatives and edit the best one for free.',limit:'X: 280 characters per caption',input:'Describe the post, audience and objective',bestFor:'Launches, updates and community posts'},
 headlines:{title:'Free AI Headline & Email Subject Generator',description:'Generate clear headlines and email subject lines from your content. Compare concise alternatives with tone controls and limits suited to each format.',limit:'110 headline / 70 subject characters',input:'Describe the article, offer or announcement',bestFor:'Newsletters, articles and landing pages'}
};
export function toolMetadata(tool:string){const t=toolCatalog.find(t=>t.id===tool);if(!t)return {title:'Tool not found',robots:{index:false,follow:false}};const s=toolSeo[t.id];const title=`${s.title} | QuickieTime`;return {title,description:s.description,alternates:{canonical:`/tools/${tool}`},openGraph:{type:'website' as const,title,description:s.description,url:`/tools/${tool}`,siteName:'QuickieTime'},twitter:{card:'summary' as const,title,description:s.description}}}
export function toolStructuredData(tool:Tool){const t=toolCatalog.find(t=>t.id===tool)!;return {'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':`${siteUrl}/tools/${tool}#page`,url:`${siteUrl}/tools/${tool}`,name:toolSeo[tool].title,description:toolSeo[tool].description,isPartOf:{'@id':`${siteUrl}/#website`},about:{'@id':`${siteUrl}/#app`}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'QuickieTime',item:siteUrl+'/'},{'@type':'ListItem',position:2,name:t.name,item:`${siteUrl}/tools/${tool}`}]}]}}
