import {z} from 'zod';
import {defaultBrief,inputSchema,type Brief,type Tool} from './config';
export const draftSchema=inputSchema.extend({idea:z.string().max(24000)});
export const starters:Record<Tool,{label:string;idea:string;context?:string}[]>={
 tagline:[{label:'Midnight coffee',idea:'A coffee shop for students, open until 3 AM.'},{label:'Pet people',idea:'A dog walking service for busy people. We send a photo after every walk.'},{label:'Tiny big ideas',idea:'Pocket-sized notebooks made from recycled paper for people who sketch ideas on the go.'}],
 rewrite:[{label:'Less corporate',idea:'We would like to inform you that we are currently in the process of updating our website. During this period, some pages may be temporarily unavailable.'},{label:'Product polish',idea:'Our backpack has a laptop pocket and it keeps rain out. It also has a side pocket for your water bottle.'},{label:'Clear announcement',idea:'The workshop is moving to Friday at 4 PM. People who booked for Thursday can use the same ticket. If Friday does not work, email us to request a refund.'}],
 summarize:[{label:'Meeting notes',idea:'The team agreed to launch the beta on Friday. Existing customers will receive invitations first. Maya will prepare the onboarding email by Wednesday. Dev will check the payment flow on Thursday. Feedback will be collected for two weeks before a wider release. No launch date has been set for the public version.'},{label:'Product update',idea:'Our mobile app update adds offline reading for saved articles. Readers can download up to 20 articles while connected to Wi-Fi. Downloads remain available for seven days. The update also improves text size controls. Offline video is not included. The update is available to all existing subscribers.'}],
 reply:[{label:'Customer question',idea:'Hi, can I change the delivery address for my order?',context:'Ask for the order number. Address changes are possible only before dispatch. Do not promise that the change is confirmed.'},{label:'Polite follow-up',idea:'Could you send me the proposal we discussed?',context:'The proposal will be ready by Thursday afternoon. Thank them for their patience.'}],
 social:[{label:'A little launch',idea:'Our neighbourhood bakery is launching a Saturday sourdough workshop. Beginners welcome; booking required.'},{label:'Behind the scenes',idea:'We make every ceramic mug by hand in our small studio. Each one is slightly different.'},{label:'Community invite',idea:'Join our free neighbourhood book swap on Sunday from 10 AM to noon. Bring a book and take a book.'}],
 headlines:[{label:'Newsletter hook',idea:'A newsletter with three practical ways to speed up a WordPress website without buying extra plugins.'},{label:'Fresh launch',idea:'A reusable water bottle with a leakproof lid and replaceable parts.'},{label:'Useful article',idea:'An article explaining how to plan a small balcony garden with limited sunlight.'}]
};
export const sampleLines:Record<Tool,{before:string;after:string;note:string}>={
 tagline:{before:'A coffee shop open until 3 AM.',after:'Bedtime called. We declined.',note:'A small line with a point of view.'},
 rewrite:{before:'We are currently in the process of updating our website.',after:'We’re updating our website.',note:'Same meaning. Less heavy lifting.'},
 summarize:{before:'A page of meeting notes, decisions and deadlines.',after:'Beta: Friday. Invitations: existing customers first. Feedback: two weeks.',note:'The decisions deserve the spotlight.'},
 reply:{before:'Can I change my delivery address?',after:'Please send your order number. We can check whether it’s still possible before dispatch.',note:'Helpful. Human. No invented promises.'},
 social:{before:'Handmade mugs. Each one is different.',after:'Matching mugs? Not our thing. Every one leaves the studio with a little character.',note:'Give the details a little personality.'},
 headlines:{before:'How to make your WordPress site faster.',after:'Three speed fixes. Zero new plugins.',note:'Give readers a reason to open.'}
};
export function readDrafts(raw:string|null):Partial<Record<Tool,Brief>>{const result:Partial<Record<Tool,Brief>>={};try{const saved=JSON.parse(raw||'{}');for(const tool of Object.keys(starters) as Tool[]){const parsed=draftSchema.safeParse(saved[tool]);if(parsed.success&&parsed.data.tool===tool)result[tool]=parsed.data}}catch{}return result}
export function nextDraft(tool:Tool,drafts:Partial<Record<Tool,Brief>>,project:string){return drafts[tool]||{...defaultBrief(tool),project}}
