export const guides: Record<string, {
    use: string;
    tips: string[];
    output: string;
    note: string;
}> = {
    tagline: { use: 'Create a short, memorable line for a business, product or event. Name the audience and one concrete difference before choosing a tone.', tips: ['Describe what makes your offer different, not just its industry.', 'Mix two or three compatible tones for a focused result.', 'Use Make it shorter to sharpen a strong concept; Make it worse explores a more absurd version.'], output: 'Your bedtime called. We declined.', note: 'A tagline should be easy to say aloud. Check that the wording is suitable for your brand and does not closely resemble another company’s slogan.' },
    rewrite: { use: 'Paste a rough paragraph and explain who will read it. The rewriter adjusts clarity, structure and tone while keeping the supplied facts.', tips: ['Include the full paragraph rather than isolated fragments.', 'Use context to specify the audience and information that must stay unchanged.', 'Choose Markdown for documents or WhatsApp for a paste-ready message.'], output: 'We’re updating our hosting plans. Your current price stays the same until your next renewal.', note: 'Compare dates, names, prices and commitments against your original text before sending. Rewriting should not change what you promised.' },
    summarize: { use: 'Condense notes, an announcement or a long paragraph into the key points. Choose a paragraph or bullet points using the structure control.', tips: ['Paste the source text, not a URL: this tool does not fetch web pages.', 'Choose Brief for essentials or Detailed for more supporting points.', 'Ask for actions and deadlines only when the source includes them.'], output: 'Beta launches Friday. Existing customers receive the first invitations. Feedback will be collected for two weeks before wider release.', note: 'Summaries can omit nuance. Keep the original available when the details matter.' },
    reply: { use: 'Draft a customer response or email from a message and the facts you provide. Add the desired next step and the tone in the context field.', tips: ['Remove passwords, payment details and other secrets before pasting.', 'State what is confirmed and what still needs investigation.', 'Specify a greeting, closing or call to action in context if needed.'], output: 'Hi, thanks for letting us know. Please share the error message and the time of your payment attempt so we can investigate.', note: 'The writer cannot inspect orders, server logs or payments. Provide verified facts and review the reply before sending.' },
    social: { use: 'Turn an announcement or idea into a concise social post. Describe the platform, audience and next action to make the caption useful.', tips: ['Include the actual offer and any conditions.', 'Ask for a specific call to action in the context field.', 'Select the platform and number of captions; X captions have a 280-character ceiling.'], output: 'Your deadline is awake. So are we. Midnight coffee delivery for students has landed. Order your late-night backup.', note: 'Review offers and availability before publishing. The tool drafts text; it does not publish to social accounts.' },
    headlines: { use: 'Explore short headline alternatives or email subject lines for the same idea. Compare different angles without generating an entire article.', tips: ['Describe the actual content so the headlines stay accurate.', 'Give the target audience and the intended benefit.', 'Avoid implying guarantees, urgency or facts that the source does not support.'], output: 'Your WordPress site, minus the waiting.\nA faster site starts with smaller fixes.\nSpeed up WordPress without the guesswork.\nWhat is slowing your website down?\nSmall changes. Shorter load times.', note: 'Choose the clearest accurate hook. A catchy subject line should still match what the reader finds inside.' }
};
