import Link from 'next/link';
import {PublicHeader} from '@/components/public-shell';
import { notFound } from 'next/navigation';
import { toolCatalog } from '@/lib/config';
import {toolMetadata,toolStructuredData,toolSeo} from '@/lib/seo';
import { guides } from '@/lib/tool-guides';
export const dynamicParams=false;
export function generateStaticParams(){return toolCatalog.map(t=>({tool:t.id}))}
export async function generateMetadata({params}:{params:Promise<{tool:string}>}){return toolMetadata((await params).tool)}
export default async function Page({ params }: {
    params: Promise<{
        tool: string;
    }>;
}) { const { tool } = await params; const t = toolCatalog.find(t => t.id === tool); if (!t)
    notFound(); const g = guides[tool];const detail=toolSeo[t.id]; return <><PublicHeader/><main className="guide-page" id="page-content"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(toolStructuredData(t.id)).replace(/</g,'\\u003c')}}/><nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">QuickieTime</Link><span aria-hidden="true">/</span><span aria-current="page">{t.name}</span></nav><span className="step-tag">LESS OVERTHINKING. BETTER WORDS.</span><h1>{detail.title}</h1><p>{g.use}</p><Link className="primary-button" href={'/?tool=' + tool}>Open {t.name.toLowerCase()} →</Link><div className="guide-facts"><div><strong>Start with</strong><span>{detail.input}</span></div><div><strong>Made for</strong><span>{detail.bestFor}</span></div><div><strong>Length that fits</strong><span>{detail.limit}</span></div></div><h2>Get a better first draft</h2><ul>{g.tips.map(t => <li key={t}>{t}</li>)}</ul><div className="guide-example"><h2>Example input</h2><p>{t.example}</p><h2>Illustrative output</h2><p className="content-output">{g.output}</p><p className="setting-hint">An editorial example, not a promise of identical AI output.</p></div><h2>Length, formatting and free credits</h2><p>Guests receive 5 credits per day. Sign in with your email for 20 daily credits and saved projects. Taglines use 5, 10 or 16 words per idea; headlines and subject lines have their own character limits. Longer drafts support up to 300 words for guests or 700 when signed in. Summaries stay shorter than the source. Optional explicit line limits apply only to replies and social captions. One generation or rewrite costs one credit; failed requests are refunded. Credits reset at midnight UTC.</p><p>Choose plain text, Markdown or WhatsApp formatting. Copy preserves the output’s line breaks and formatting markers. A line means an explicit line break, not wrapping on your phone.</p><h2>Before you use the output</h2><p>{g.note}</p><h2>Your work stays yours to manage</h2><p>Guest history stays in the current browser. Signed-in work is saved privately in the dashboard, where you can search all saved history, filter by tool, date and project, manage projects, continue editing, save versions or delete an item. Drafts are sent to our AI provider to generate the result. Do not submit passwords or sensitive personal data.</p><h2>Explore the other tools</h2><ul>{toolCatalog.filter(x => x.id !== tool).map(x => <li key={x.id}><Link href={'/tools/' + x.id}>{x.name}</Link> — {x.description}</li>)}</ul></main></>; }
